
train:
  learning_rate: 0.01
  batch_size: 4
  num_workers: 4
  n_epochs: 100
  data_path: "../Data/"
  checkpoints_path: "./checkpoints/" 
val:
  data_path: "../Data/"
  checkpoints_path: "./checkpoints/iter/best.pth"
  batch_size: 1
  num_workers: 0


